language: java
sudo: false

jdk:
- openjdk10

cache:
  directories:
  - "$HOME/.m2"

addons:
  sonarcloud:
    organization: "dexmo007-github"

script: mvn clean verify -B
after_success:
- mvn clean test jacoco:report coveralls:report
- sonar-scanner